### ISSUE TITLE
Support BNC Connection

### ISSUE THREAD

**Issue by flavioribeiro** [hachibasu/koko#10]
I'm trying to use Koko with my bnc ([znc](http://wiki.znc.in/ZNC)) but it seems that "/quote" commands are not supported yet. It would be great if I could connect to it, and better if we could set some `onConnect` commands to automate this work. 

![image](https://cloud.githubusercontent.com/assets/244265/7814413/6315e088-0398-11e5-9a30-827037b3fe5d.png)

**Comment by noraesae** [comment]
`onConnect` commands will be supported in the near future, but neither yet implemented or planned. I'll work on `/quote` (or `/raw`) and they will be implemented soon!

Thanks!

**Comment by flavioribeiro** [comment]
Awesome, tell me if you want help. I've never did anything with Electron but I can take a look on it.

**Comment by noraesae** [comment]
Thanks. Then can I have a server host where I can test the command? It may help me check if the implementation actually works well.

**Comment by flavioribeiro** [comment]
sent directly to ur email

**Comment by noraesae** [comment]
Implemented. `node_modules/irc` should be reinstalled to use the feature.

It will be included in the next release. Thanks!

**Comment by noraesae** [comment]
Also, I've tested with your server and it worked well. Now you may want to remove the temporary account :smile: Cheers

**Comment by flavioribeiro** [comment]
Awesome, thank you for this. Gonna wait for the next release to install it here .

**Comment by noraesae** [comment]
Released as the latest version, `v0.1.15`.

Cheers
