### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by winkler1** [hachibasu/koko#11]
Hi,
 Have not seen Electron before, but tried `./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron .` -- and it says "Error opening app"... that the dir does not have a valid electron app.
 Could there be a quick paragraph in the README for newbies to run it?
Thanks

**Comment by noraesae** [comment]
If you're using OS X or Linux, then just `make; make run` will work. Windows is not yet supported :cry: 

For the detail, please refer to [CONTRIBUTION.md](https://github.com/hachibasu/koko/blob/master/doc/CONTRIBUTION.md) and [USERGUIDE.md](https://github.com/hachibasu/koko/blob/master/doc/USERGUIDE.md).

Cheers!
