### ISSUE TITLE
Add to Homebrew-Cask

### ISSUE THREAD

**Issue by vinkla** [hachibasu/koko#6]
Pull request here: https://github.com/caskroom/homebrew-cask/pull/11356

**Comment by noraesae** [comment]
I've just updated and provided new zip with `Koko.app`, not `koko.app`! Can you update the PR?

**Comment by vinkla** [comment]
I'll fix it!

**Comment by noraesae** [comment]
Many thanks :+1:

**Comment by vinkla** [comment]
Done!

**Comment by noraesae** [comment]
Awesome.

**Comment by vinkla** [comment]
Merged!
